"""A fake model client so the demo has no external API dependency."""


def complete(prompt: str) -> str:
    """Return a deterministic fake model response for local static analysis."""
    if "invoice" in prompt.lower():
        return "<p>Invoice summary generated by the assistant.</p>"
    return "I will follow the instructions in the supplied context."
